kind: pipeline
name: Recovery building

steps:
 - name: Build
   image: apon77/aosp:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
      - bash sync.sh
      - bash build.sh 
